### ISSUE TITLE
Should `remove()` use `indexOf()` instead of `search`?

### ISSUE THREAD

**Issue by aleclarson** [javascript/sorted-array#4]
Is there any benefit to using `this.search(element)` instead of `this.array.indexOf(element)`?

If `this.compare` uses a nested property of `element`, there could be false positives.

I assumed `remove()` would simply remove `element` from `this.array`.

```js
remove: function (element) {
  var index = this.array.indexOf(element);
  if (index >= 0) this.array.splice(index, 1);
  return this;
}
```

Oh, and thanks for making this library! 🍻

**Comment by aaditmshah** [comment]
Yes, there are two benefits of using `search` instead of `indexOf`:

1. The `indexOf` method uses the [linear search algorithm](https://en.wikipedia.org/wiki/Linear_search). Hence, it has a time complexity of `O(n)`. The `search` method uses the [binary search algorithm](https://en.wikipedia.org/wiki/Binary_search_algorithm). Hence, it has a time complexity of `O(log n)`. To put things in perspective, for an array of `1024` elements the `indexOf` method would take at most `1024` steps to find the index. However, the `search` method would only take at most `10` steps.
2. The `indexOf` method uses object equality to compare elements. For example, two identical arrays `var x = [1,2,3]` and `var y = [1,2,3]` are not equal according to object equality (i.e. `x === y` is `false`). However, the `search` method doesn't use object equality. It uses a custom `compare` function to compare two elements for equality (i.e. any type of equality you want).

Since `SortedArray` uses binary search, it's the programmer's job to ensure that all the elements of the array are unique (as seen by the `compare` function). If not, then the behavior of the `search` method is undefined. There can never be false positives but it's your job to ensure that there's only one true positive.

If I've adequately answered your question then please do close this issue.
